import { CommandInterface } from "../interfaces/command";
import { SlashCommandBuilder } from "@discordjs/builders";
const flowerquotes = ["Onward and upward!", "What a beautiful day.", 'Oh, was it something I said?', "That Goomba looks so serene.", "Well then.", "Mmm, refreshing!", "Ahaha!", "Oh!", "Coiiiiins!", "Would ya look at that!", "Heyyyy!", "Well, that was something.", "Hiiii!", "Thank you! That trunk sure is useful, huh?", "I want some water too!", "Waterrrr!", "Whoa...", "Whoa!", "Whoa-whoa!", "What's that?", "Hey, you! What WAS that?","Didn't you see something back there?","Are you just gonna leave?","Bye-bye!", "So long!", "Wonder if you can get over there...", "So you CAN get over there!", "Walking plants, huh?\nAlmost as weird as talking plants.", "Ooh, that's a pretty flower.\nUmmmm...\nAre they... singing?\nThey're singing.", "Ouch!","Hey!", "Agh!", "Stop!", "I said stop!", "Wait a sec!\nHow'd you get over here?","You should come back sometime.","Heeeey!\nWhat are you doing?", "I want some water too!", "https://www.youtube.com/watch?v=CkrxL0agI18", "Love that sound!", "Ya found me!\nDid I surprise you?","Bored, bored, bored.","Wow!","Something feels...off...","OooOOaaaAAH!","AaaaAAaaAAAH!","Hey, someone to talk to!","Farewell, lonely days!","Heya!","Boing!","Hi!","How'd you get up here?!","Ah, what a peaceful day.","AaaAAh!","Waaaah!","Wh-what's happening?!", "There's so many of them!\nDo Something!","Phew!","Well done!","Zzz...","What is it?", "Can't a guy get some shut-eye around here?", "This is so wonderful!","So shiny!","Look at you--walkin' on air!","You should keep going!", "Wheeeee!", "Clinky, clinky!", "So many of them!", "Make sure you don't miss any!","Ohhhh!","What's this?\nNever seen anything like it...","*sniff* *sniff* *sniff*\nAh...\nNow, that's a good smell.","So many creepy-crawlies...", "They just keep coming!", "Will it ever end?", "I love this place.\nNothin' to do but relax.","EyaaaAAaah!","How is this happening?!","Phew! I'm fine. Everything's fine.","What ARE they?","Keep going!","What IS all this?!","Was it all a dream?","Feel like you're missing something?","So long!", "Score!","That worked out.", "Love that sound!", "Hey!","This pipe -- It can't hold us!","Huh?\nWhat's this?","Oooh!\nIt's kinda catchy!","You ready?\nHere we go!","OoooOOh!\nmy!\nAaaaall..\nright!","Hehe. That was fun.","Huh?\nWhy'd you come this way?","Nice job!\nYou came the cool way!","Oh this isn't good!\nThis snow--\n**IT'S BURYING MEEEEE!**","Aah!\nWe're saved!","Are they after me?\nNah, it's gotta be you.","That looked terrifying!\nYou must be sweatin","Nice job!\nYa did great back there.\nThis is kinda fun.\n**Aaaaah!**\nWell that was something.","Yay!", "They say the ocean tastes like tears.", "Wanna swim with me?", "Splish-splash!", "Love this swimming hole!\nBut its kinda crowded lately...","What a rush... I LIKE it.", "Ha! They're copying you.","**AaaaAAaaAAAH!**\n**I'm falliiiing!**\nAaaaah!\nAaaaAAaa-*Falls out of the world.*\n","So many shooting stars...\nThey bring good luck!"];
// https://www.mariowiki.com/List_of_Talking_Flower_quotes
export const talkingflower: CommandInterface = {
  data: new SlashCommandBuilder()
    .setName("talkingflower")
    .setDescription("What does the talking flower say? (spoilers for super mario wonder)"),

  run: async (interaction) => {
    await interaction.reply('<:TalkingFlower:1198733722598514778> '+flowerquotes[Math.floor(Math.random() * flowerquotes.length)]);
  }, 
};
